[2024-12-17T19:22:39.889+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-12-17T19:22:39.938+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2024-12-17T19:22:39.963+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-17T19:22:39.990+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T19:22:36.141404+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-12-17T19:22:39.991+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T19:22:36.141404+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-12-17T19:22:40.022+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T19:22:36.141404+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-12-17T19:22:40.023+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T19:22:36.141404+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-12-17T19:22:40.024+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T19:22:36.141404+00:00 [queued]>
[2024-12-17T19:22:40.025+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T19:22:36.141404+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-12-17T19:22:40.040+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T19:22:36.141404+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-12-17T19:22:40.049+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T19:22:36.141404+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-12-17T19:22:40.051+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T19:22:36.141404+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-12-17T19:22:40.059+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T19:22:36.141404+00:00 [queued]>
[2024-12-17T19:22:40.063+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-17T19:22:40.089+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_all_user_data> on 2024-12-17 19:22:36.141404+00:00
[2024-12-17T19:22:40.104+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=331) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-17T19:22:40.104+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiktok_dag', 'fetch_all_user_data', 'manual__2024-12-17T19:22:36.141404+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/tiktok_dag.py', '--cfg-path', '/tmp/tmprxawlnhp']
[2024-12-17T19:22:40.107+0000] {standard_task_runner.py:72} INFO - Started process 333 to run task
[2024-12-17T19:22:40.108+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask fetch_all_user_data
[2024-12-17T19:22:40.113+0000] {cli_action_loggers.py:79} DEBUG - Calling callbacks: [<function default_action_log at 0x7f3674785da0>]
[2024-12-17T19:22:40.187+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-17T19:22:36.141404+00:00 [running]> on host b221d1600292
[2024-12-17T19:22:40.251+0000] {taskinstance.py:2384} DEBUG - Clearing XCom data
[2024-12-17T19:22:40.267+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-12-17T19:22:40.336+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-12-17T19:22:40.379+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiktok_dag' AIRFLOW_CTX_TASK_ID='fetch_all_user_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-17T19:22:36.141404+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-17T19:22:36.141404+00:00'
[2024-12-17T19:22:40.384+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-12-17T19:22:40.385+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-12-17T19:22:40.387+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-17T19:22:40.471+0000] {tiktok_dag.py:51} INFO - Fetching data for all usernames...
[2024-12-17T19:22:40.501+0000] {tiktok_dag.py:53} INFO - Usernames pulled from XCom: ['mrbeast', 'jadeanna', 'feyenoord']
[2024-12-17T19:22:40.504+0000] {tiktok_dag.py:59} INFO - Fetching data for username: mrbeast
[2024-12-17T19:22:40.505+0000] {tiktok_etl.py:106} INFO - Checking token expiry: {'token': None, 'expires_at': None}
[2024-12-17T19:22:40.506+0000] {tiktok_dag.py:64} ERROR - Error fetching data for username mrbeast: 'TIKTOK'
Traceback (most recent call last):
  File "/opt/airflow/dags/tiktok_dag.py", line 61, in fetch_all_user_data
    te.tiktok_get_user_info(username=username, output_dir=OUTPUT_DIR, **context)
  File "/opt/airflow/dags/tiktok_etl.py", line 119, in tiktok_get_user_info
    client_key = config["TIKTOK"]["CLIENT_KEY"]
                 ~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.12/configparser.py", line 941, in __getitem__
    raise KeyError(key)
KeyError: 'TIKTOK'
[2024-12-17T19:22:40.523+0000] {tiktok_dag.py:59} INFO - Fetching data for username: jadeanna
[2024-12-17T19:22:40.524+0000] {tiktok_etl.py:106} INFO - Checking token expiry: {'token': None, 'expires_at': None}
[2024-12-17T19:22:40.525+0000] {tiktok_dag.py:64} ERROR - Error fetching data for username jadeanna: 'TIKTOK'
Traceback (most recent call last):
  File "/opt/airflow/dags/tiktok_dag.py", line 61, in fetch_all_user_data
    te.tiktok_get_user_info(username=username, output_dir=OUTPUT_DIR, **context)
  File "/opt/airflow/dags/tiktok_etl.py", line 119, in tiktok_get_user_info
    client_key = config["TIKTOK"]["CLIENT_KEY"]
                 ~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.12/configparser.py", line 941, in __getitem__
    raise KeyError(key)
KeyError: 'TIKTOK'
[2024-12-17T19:22:40.535+0000] {tiktok_dag.py:59} INFO - Fetching data for username: feyenoord
[2024-12-17T19:22:40.536+0000] {tiktok_etl.py:106} INFO - Checking token expiry: {'token': None, 'expires_at': None}
[2024-12-17T19:22:40.537+0000] {tiktok_dag.py:64} ERROR - Error fetching data for username feyenoord: 'TIKTOK'
Traceback (most recent call last):
  File "/opt/airflow/dags/tiktok_dag.py", line 61, in fetch_all_user_data
    te.tiktok_get_user_info(username=username, output_dir=OUTPUT_DIR, **context)
  File "/opt/airflow/dags/tiktok_etl.py", line 119, in tiktok_get_user_info
    client_key = config["TIKTOK"]["CLIENT_KEY"]
                 ~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.12/configparser.py", line 941, in __getitem__
    raise KeyError(key)
KeyError: 'TIKTOK'
[2024-12-17T19:22:40.542+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-17T19:22:40.544+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2024-12-17T19:22:40.560+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-17T19:22:40.566+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tiktok_dag, task_id=fetch_all_user_data, run_id=manual__2024-12-17T19:22:36.141404+00:00, execution_date=20241217T192236, start_date=20241217T192240, end_date=20241217T192240
[2024-12-17T19:22:40.589+0000] {cli_action_loggers.py:98} DEBUG - Calling callbacks: []
[2024-12-17T19:22:40.649+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-17T19:22:40.708+0000] {dagrun.py:968} DEBUG - number of tis tasks for <DagRun tiktok_dag @ 2024-12-17 19:22:36.141404+00:00: manual__2024-12-17T19:22:36.141404+00:00, state:running, queued_at: 2024-12-17 19:22:36.422053+00:00. externally triggered: True>: 2 task(s)
[2024-12-17T19:22:40.710+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-17T19:22:40.734+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
